### ISSUE TITLE
R2MultiBUGS always fail with "not updated to be able to change RN generator"

### ISSUE THREAD

**Issue by hszest** [MultiBUGS/R2MultiBUGS#1]
MultiBUGS will stop with the following message:

BugsCmds.SetDisplay('log')

BugsCmds.SetFilePath('____________.txt' ); BugsCmds.ParseGuard; BugsCmds.Parse
model is syntactically correct

BugsCmds.SetFilePath('____________.txt' ); BugsCmds.LoadDataGuard; BugsCmds.LoadData
data loaded

BugsCmds.CompileGuard; BugsCmds.specificationDialog.numChains  := 2; BugsCmds.Compile
model compiled in 0 s

BugsCmds.SetRNGuard; BugsCmds.SetRNState(1)
model must have been compiled but not updated to be able to change RN generator
script failed

And if I remove the `modelSetRN(1)` from the generated script, then MultiBUGS can run.

**Comment by rjbgoudie** [comment]
R2MultiBUGS requires MultiBUGS 1.0, which is not yet released. Given the error message, I think you were probably using MultiBUGS 0.9. The fix for this issue was MultiBUGS/MultiBUGS@d667f87c1d02577b1341e06d847a15fefef9540e . Please resubmit the issue if it persists once 1.0 is released.
