### ISSUE TITLE
Help pages missing in current release

### ISSUE THREAD

**Issue by hszest** [MultiBUGS/R2MultiBUGS#3]
The help page is missing in the R help and reads "There are no help pages in this package"
I'm now reading the info in the R files in this pacakge to get help info.
Please have a look into this issue, thanks.

**Comment by hszest** [comment]
It turns out that I have to run the roxygen myself...
The following R commend can fix this issue (first unzip the source file)
```
roxygen2::roxygenise(path)
devtools::install_local(path)
```

**Comment by hszest** [comment]
Also a piece of mismatched info was found in the DESCRIPTION file:
> SystemRequirements: MultiBUGS (>= 0.9)
It seems that the supported version should be >= 1.0

**Comment by rjbgoudie** [comment]
> Also a piece of mismatched info was found in the DESCRIPTION file:
> 
> > SystemRequirements: MultiBUGS (>= 0.9)
> 
> It seems that the supported version should be >= 1.0

Fixed by e8fd66d7eb8f269a1eb4320676a717199b1c9821. Thanks for reporting.
