### ISSUE TITLE
Error occures with 'debug = TRUE' option

### ISSUE THREAD

**Issue by hszest** [MultiBUGS/R2MultiBUGS#4]
Using the latest build of MultiBUGS with the latest R2MultiBUGS

If 'debug = FALSE' everything seems fine, but with 'debug = FALSE' then following messages was displayed in R console:
```
Error in bugs.run(n.burnin, MultiBUGS.pgm, debug = debug, WINE = WINE,  : 
  Look at the log file in  D:/HONG/SLR  and
try again with 'debug=TRUE' to figure out what went wrong within MultiBUGS.
```

**Comment by rjbgoudie** [comment]
Thanks for the report. I assume you mean debug=TRUE wasn't working. If so, should be fixed by aff8f5a24fccbedc1471e14eb0ed5cd29a6e5b7b
